# Makerfabs
i2c:
  sda: 4
  scl: 5

uart:
  id: uart_pm25
  tx_pin: 22
  rx_pin: 21
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sensor:
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_pm25
    pm_2_5:
      name: "Makerfabs PM2.5 Sensor"
      unit_of_measurement: 'ug/m3'
      accuracy_decimals: 1
    update_interval: 30s
  
  - platform: aht10
    temperature:
      name: "Makerfabs Temperature"
    humidity:
      name: "Makerfabs Humidity"
    update_interval: 10s

  - platform: pulse_counter
    pin: 27
    name: "Wind Speed"
    unit_of_measurement: 'm/s'
    filters:
      - multiply: 0.002

  - platform: bmp280
    pressure:
      name: "Outside Pressure"
    address: 0x76
    update_interval: 10s
